@extends('master')
@section('page_title', 'products')

@section('content')
    <h4 class='alert alert-success'>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Doloribus harum incidunt, iste laboriosam dicta unde, exercitationem a quos tenetur reiciendis reprehenderit dolores eos sit deleniti animi dolorem laborum doloremque expedita quidem, maxime veniam ipsum! Distinctio saepe nemo nulla architecto maiores dignissimos voluptates sed ab quod commodi velit recusandae iusto voluptatum, doloremque, sunt est. Eum nam ab iste aspernatur iure reiciendis ipsum illum molestiae possimus perferendis nostrum dolor rem a assumenda fugiat enim atque et, temporibus excepturi sequi quae quibusdam quas! Voluptatibus fugit quis repellat facilis id, maxime at possimus voluptates officiis voluptatem itaque nihil dolore excepturi quas velit quaerat reiciendis vero quam neque asperiores suscipit autem eum vitae quibusdam? Praesentium soluta autem quis consectetur error, fugiat pariatur a culpa sint fuga illum distinctio molestias possimus amet provident, debitis similique? Consequatur iusto ullam non vitae esse beatae vel, commodi ab nulla eum optio impedit aliquid veritatis reprehenderit dolor eius ducimus recusandae perferendis, ut, asperiores dignissimos. Doloribus, quaerat voluptas. Impedit et, nihil amet sequi ad dolor! Quisquam necessitatibus odit est dolorum quod culpa amet, optio enim libero quasi rem aut non officiis inventore commodi voluptatem eligendi maxime facilis quaerat similique. Sed explicabo enim natus ab voluptatibus, provident a, voluptates architecto facilis, quae nostrum quos temporibus tenetur porro cumque doloribus suscipit! Quidem placeat pariatur eaque alias amet, tempora beatae quod numquam. Accusamus adipisci dolorem est voluptatem quia esse quos nam explicabo? Nulla qui minus ipsa dolorum veritatis, ratione tempore possimus repellat! Quos eligendi numquam nulla magnam hic ratione quibusdam enim iure quis officia ea voluptatum rem laudantium at minima est nobis voluptas, quaerat, delectus iusto eos. Vel, in doloribus. Autem rem, fugit ipsam ex optio veritatis obcaecati quidem, nostrum facilis hic labore vero nemo voluptatibus deleniti beatae cum velit nobis ab perspiciatis natus fuga itaque quaerat accusantium et! Exercitationem labore repellat ratione omnis facilis cupiditate rerum, optio illo. Molestiae doloribus deleniti nobis eum optio minima, iste consectetur voluptates animi ratione voluptas fugit consequatur, rem quos ipsum. Laudantium distinctio quas aut ipsam praesentium pariatur minima blanditiis nobis sequi consequuntur earum error eligendi doloribus atque corrupti esse tenetur fuga nostrum, placeat tempore nesciunt voluptatem aliquam ab eos? Ut iusto iste consectetur? Voluptates odit, ipsam culpa iure rerum ratione, inventore totam sequi quaerat impedit repellendus cupiditate nostrum aliquam similique voluptas. Harum itaque sint tenetur quis. Reiciendis quibusdam ea enim doloremque repellat iusto consequatur, quidem numquam obcaecati molestias eos ex dolores, commodi, possimus saepe. Eius, eum delectus!
    </h4>
@stop

@section('footer')

@stop
